-- Migration 002: nightly session report scheduler
-- DEPRECATED — replaced by Vercel Cron Jobs (vercel.json crons config)
--
-- The original pg_cron approach required enabling the pg_cron extension in
-- Supabase (Database → Extensions), which is not enabled by default.
--
-- The replacement uses Vercel's native cron job support:
--   - Schedule defined in vercel.json: "crons": [{"path": "/api/cron/session_report", "schedule": "0 21 * * *"}]
--   - Handler: api/cron_session_report.py
--   - Auth: CRON_SECRET env var (set automatically by Vercel)
--   - Config: REPORT_CONFIGS env var — JSON array of {owner, recipients}
--     e.g. [{"owner": "annie", "recipients": ["mike@example.com"]}]
--
-- No SQL migration is required. Set REPORT_CONFIGS in Vercel environment variables.
--
-- Original pg_cron approach (kept for reference):
--
-- SELECT cron.schedule(
--   'annie-nightly-session-report',
--   '0 21 * * *',
--   $$
--   SELECT net.http_post(
--     url := 'https://<VERCEL_URL>/session_report',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'Authorization', 'Bearer <PARENT_API_TOKEN>'
--     ),
--     body := jsonb_build_object(
--       'report_type', 'study_session',
--       'owner', 'annie',
--       'recipients', jsonb_build_array('<PARENT_EMAIL>')
--     )
--   );
--   $$
-- );
